// layout.tsx — Layout racine de l’app (App Router)
// - Ajoute les polices
// - Injecte les styles globaux
// - Monte le provider CopilotKit pour activer l’agent côté front (optionnel si aucune clé/URL fournie)
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CopilotKit } from "@copilotkit/react-core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const runtimeUrl = process.env.NEXT_PUBLIC_COPILOT_RUNTIME_URL;
  const publicApiKey = process.env.NEXT_PUBLIC_COPILOT_PUBLIC_API_KEY;
  const publicLicenseKey = process.env.NEXT_PUBLIC_COPILOT_PUBLIC_LICENSE_KEY;
  const hasCopilotConfig = Boolean(runtimeUrl || publicApiKey || publicLicenseKey);

  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {hasCopilotConfig ? (
          <CopilotKit
            runtimeUrl={runtimeUrl}
            publicApiKey={publicApiKey}
            publicLicenseKey={publicLicenseKey}
          >
            {children}
          </CopilotKit>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
